#!/bin/bash
# ==============================================================================
# Database Restore Script for DIGIT PostgreSQL
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load Environment variables
if [ -f "$ROOT_DIR/.env" ]; then
    export $(grep -v '^#' "$ROOT_DIR/.env" | xargs)
fi

DB_USER=${POSTGRES_USER:-postgres}
DB_NAME=${POSTGRES_DB:-digit_db}

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0;m' # No Color

BACKUP_FILE=$1

if [ -z "$BACKUP_FILE" ]; then
    echo -e "${RED}Error: Please specify the path to the backup file to restore.${NC}"
    echo "Usage: ./scripts/restore-db.sh <path_to_backup_file> [target_database_name]"
    exit 1
fi

if [ ! -f "$BACKUP_FILE" ]; then
    echo -e "${RED}Error: Backup file '$BACKUP_FILE' does not exist.${NC}"
    exit 1
fi

# Check if postgres container is running
if [ "$(docker inspect --format='{{.State.Status}}' digit-postgres 2>/dev/null)" != "running" ]; then
    echo -e "${RED}Error: digit-postgres container is not running. Please start the infrastructure first.${NC}"
    exit 1
fi

TARGET_DB=$2

# Determine file type and execute restore
if [[ "$BACKUP_FILE" == *.gz ]]; then
    echo -e "${YELLOW}Detected gzipped backup. Extracting and restoring...${NC}"
    
    if [ -n "$TARGET_DB" ]; then
        echo "Restoring single database '$TARGET_DB'..."
        gunzip -c "$BACKUP_FILE" | docker exec -i digit-postgres psql -U "$DB_USER" -d "$TARGET_DB"
    else
        echo "Restoring full database cluster dump..."
        gunzip -c "$BACKUP_FILE" | docker exec -i digit-postgres psql -U "$DB_USER"
    fi
else
    # Custom format restore (often generated by pg_dump -F c)
    # Check if the file signature matches PostgreSQL custom format (starts with 'PGDMP')
    file_signature=$(head -c 5 "$BACKUP_FILE")
    
    if [ "$file_signature" == "PGDMP" ]; then
        if [ -z "$TARGET_DB" ]; then
            echo -e "${RED}Error: Custom pg_dump formats require specifying a target database.${NC}"
            echo "Usage: ./scripts/restore-db.sh <path_to_backup_file> <target_database_name>"
            exit 1
        fi
        echo -e "${YELLOW}Detected pg_dump custom binary format. Restoring using pg_restore...${NC}"
        docker exec -i digit-postgres pg_restore -U "$DB_USER" -d "$TARGET_DB" --clean --no-owner --no-privileges < "$BACKUP_FILE"
    else
        # Standard raw SQL text file
        if [ -n "$TARGET_DB" ]; then
            echo -e "${YELLOW}Restoring raw SQL into database '$TARGET_DB'...${NC}"
            docker exec -i digit-postgres psql -U "$DB_USER" -d "$TARGET_DB" < "$BACKUP_FILE"
        else
            echo -e "${YELLOW}Restoring raw SQL full cluster dump...${NC}"
            docker exec -i digit-postgres psql -U "$DB_USER" < "$BACKUP_FILE"
        fi
    fi
fi

if [ $? -eq 0 ]; then
    echo -e "${GREEN}[✔] Database restore completed successfully!${NC}"
else
    echo -e "${RED}[✘] Database restore failed.${NC}"
    exit 1
fi

exit 0
